// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs_SY5X46I6L1-OnTLhJsU7DktKzcO9Jg',
    appId: '1:747530498600:web:8bb7346b0f6b349d8ebb1d',
    messagingSenderId: '747530498600',
    projectId: 'atlantic-a06ba',
    authDomain: 'atlantic-a06ba.firebaseapp.com',
    storageBucket: 'atlantic-a06ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCot8fAwHuQh30mI8uvhtJvnh4jstrABWQ',
    appId: '1:747530498600:android:497bf2808d1346088ebb1d',
    messagingSenderId: '747530498600',
    projectId: 'atlantic-a06ba',
    storageBucket: 'atlantic-a06ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVFdclzZWxlLwAhrpLwMp6ByWVwAl8Gmw',
    appId: '1:747530498600:ios:d154b630ada6f27c8ebb1d',
    messagingSenderId: '747530498600',
    projectId: 'atlantic-a06ba',
    storageBucket: 'atlantic-a06ba.appspot.com',
    iosClientId: '747530498600-tpsvpf65cldp5tht16fb88kc4lrujp1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.atlanticV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVFdclzZWxlLwAhrpLwMp6ByWVwAl8Gmw',
    appId: '1:747530498600:ios:d154b630ada6f27c8ebb1d',
    messagingSenderId: '747530498600',
    projectId: 'atlantic-a06ba',
    storageBucket: 'atlantic-a06ba.appspot.com',
    iosClientId: '747530498600-tpsvpf65cldp5tht16fb88kc4lrujp1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.atlanticV2',
  );
}
